# App
spring.application.name=DOSW-ParcialT2
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://juanmelos_db_user:Zak**02**aria@cluster0.heqzhbt.mongodb.net/sportlife_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=sportlife_db


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagge